### ISSUE TITLE
Pip installation error

### ISSUE THREAD

**Issue by QuantumMisaka** [atomly-materials-research-lab/GPTFF#1]
When I try to install GPTFF by doc., this error occurs
```
(gptff) mikoto@amd-cpu:/data/chem_software/deepmodeling/GPTFF$ pip install .
Processing /data/chem_software/deepmodeling/GPTFF
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      configuration error: `project.version` must be pep440
      DESCRIPTION:
          The version of the project as supported by :pep:`440`.
      
      GIVEN VALUE:
          "1.0.1(Kawagarbo)"
      
      OFFENDING RULE: 'format'
      
      DEFINITION:
          {
              "type": "string",
              "format": "pep440"
          }
      
      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html
      
      Traceback (most recent call last):
        File "/data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 158, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 603, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 70, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 135, in read_configuration
          validate(subset, filepath)
        File "/tmp/pip-build-env-v32ypmzu/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 59, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.version`.
      configuration error: `project.version` must be pep440
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(gptff) mikoto@amd-cpu:/data/chem_software/deepmodeling/GPTFF$ pip install --upgrade pip setuptools
Requirement already satisfied: pip in /data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages (24.0)
Collecting pip
  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: setuptools in /data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages (72.1.0)
Downloading pip-24.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 8.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-24.2
(gptff) mikoto@amd-cpu:/data/chem_software/deepmodeling/GPTFF$ pip install .
Processing /data/chem_software/deepmodeling/GPTFF
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      configuration error: `project.version` must be pep440
      DESCRIPTION:
          The version of the project as supported by :pep:`440`.
      
      GIVEN VALUE:
          "1.0.1(Kawagarbo)"
      
      OFFENDING RULE: 'format'
      
      DEFINITION:
          {
              "type": "string",
              "format": "pep440"
          }
      
      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html
      
      Traceback (most recent call last):
        File "/data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/softwares/miniconda3/envs/gptff/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 158, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 603, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 70, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 135, in read_configuration
          validate(subset, filepath)
        File "/tmp/pip-build-env-c3r40hue/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 59, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.version`.
      configuration error: `project.version` must be pep440
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

How can I solve it ?

**Comment by fkxie** [comment]
Please re-clone the repo and try to install again, we have update the repo. 

If you have any problems when installation, please let me know.

**Comment by QuantumMisaka** [comment]
it seems ok
